### PR TITLE
[MIDDLEWARE] Middleware for Authenticated Users

### PR DESCRIPTION
**Pull request by kamp3r**
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT246/boards/336?modal=detail&selectedIssue=OT246-26

AS authenticated user
I WANT to restrict access to certain content
TO keep data protected

Criteria of acceptance:
It should check if the request contains the token corresponding to a user, otherwise it should return an error code 403 with an error message.

### EVIDENCE

If token is invalid, catch takes error from verifyToken and show it

test6

if token is empty, the error message was changed to 'You are not authorized to access this resource'
test7

On sucess! the message you see in the screenshot is from the test route, in case of success it will show the corresponding content
test8

### CODE REVIEW

**Review by gabodmc — APPROVED** [review]

**Review by ghnoob — COMMENTED** [review]
La verdad no me convence mucho que tire un 500 cuando el token no es valido. A mi parecer tendria que tirar un 401 o 403

**Comment by kamp3r** [comment]
> La verdad no me convence mucho que tire un 500 cuando el token no es valido. A mi parecer tendria que tirar un 401 o 403

fixed my friend

**Review by bgalacho — APPROVED** [review]
Crack!

**Review by ignacioborraz — APPROVED** [review]
todo excelentemente bien

**Pull request merged**
