### PR TITLE
[SEED] User's seeder OT246-77

### PR DESCRIPTION
**Pull request by ignacioborraz**
AS admin user
I WANT to view test data
TO be able to test functionalities on the web.

Criteria of acceptance:
Create a seeder to populate the database with Users for testing. 10 standard and 10 regular users. Later, add their data in the README.md to allow other Members to use them

image

### CODE REVIEW

**Review by ghnoob — CHANGES_REQUESTED** [review]
Cifraria las contraseñas con bcrypt para que se puedan usar en el login

**Review by gabodmc — CHANGES_REQUESTED** [review]
Si no las pasan con bcript, no les va a logear nunca

**Comment by ignacioborraz** [comment]
> Si no las pasan con bcript, no les va a logear nunca

corregido!

**Review by ghnoob — CHANGES_REQUESTED** [review]
Falta agregar los datos al readme

**Review by ghnoob — APPROVED** [review]

**Review by Samuel0023 — APPROVED** [review]

**Review by gabodmc — APPROVED** [review]

**Review by tomasignacioc — APPROVED** [review]

**Pull request merged**
